version: '3.9'
services: 
  dev: 
    image: node:latest
    volumes: 
      - .:/application
    environment:
      - NODE_ENV=development
    working_dir: /application
    command: node index.js
    ports: 
      - 3000:3000
  db: 
    image: mysql
    ports: 
      - 3306:3306
    env_file:
      .env
