version: '3.9'
services: 
  dev: 
    image: node:latest
    volumes: 
      - ./backend:/application
    environment:
      - NODE_ENV=development
    working_dir: /application
    command: bash -c "npm run build && node ."
    ports: 
      - 3000:3000
  db: 
    image: mysql
    volumes: 
      - ./database:/application
    ports: 
      - 3306:3306
    env_file:
      .env
